const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_PENDING = "LOGIN_PENDING";
const LOGIN_FAILED = "LOGIN_FAILED";
const NEXT_PAGE = "NEXT_PAGE";
const PREV_PAGE = "PREV_PAGE";

const actionType ={
  LOGIN_SUCCESS,
  LOGIN_PENDING,
  LOGIN_FAILED,
  NEXT_PAGE,
  PREV_PAGE,
};
export default actionType;
